# References:
#   * https://github.com/DavidAnson/markdownlint?tab=readme-ov-file#rules--aliases
#   * https://spec.commonmark.org/

blanks-around-fences:
  list_items: false
first-line-heading: true
line_length:
  line_length: 88
  code_blocks: false
list-marker-space:
  ol_multi: 1
  ol_single: 1
  ul_multi: 1
  ul_single: 1
no-duplicate-heading:
  siblings_only: true
no-inline-html:
  allowed_elements:
    - "br"
    - "a"
    - "code"
no-trailing-spaces: true
ol-prefix:
  style: "ordered"
ul-indent:
  indent: 2
ul-style:
  style: "dash"
